### ISSUE TITLE
Publish Maven artifacts to Maven central

### ISSUE THREAD

**Issue by lewismc** [kohsah/akomantoso-lib#10]
It would be easy for other projects to consume akomantoso-lib if we could publish Maven artifacts to Maven central.
I'll work on a patch for this and get it posted.

**Comment by kohsah** [comment]
I actually publish it as a maven artifact : (http://repo1.maven.org/maven2/io/github/kohsah/akomantoso-lib/)

Will update it for the current version ... its slightly out of date on maven

**Comment by lewismc** [comment]
Nice one thanks

On Thursday, June 18, 2015, kohsah <notifications@github.com> wrote:

> I actually publish it as a maven artifact : (
> http://repo1.maven.org/maven2/io/github/kohsah/akomantoso-lib/)
>
> Will update it for the current version ... its slightly out of date on
> maven
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kohsah/akomantoso-lib/issues/10#issuecomment-113176913>
> .
>


-- 
*Lewis*

**Comment by kohsah** [comment]
1.0.13 is on maven central now : 
```
<dependency>
  <groupId>io.github.kohsah</groupId>
  <artifactId>akomantoso-lib</artifactId>
  <version>1.0.13</version>
</dependency>
```
Note that if you set maven to pickup "latest" it won't pick-up 1.0.13, you have to set version number explicitly..since maven-metadata.xml is not updated on central (there are various issues with setting latest in maven-metadata ... so I don't bother with that)

**Comment by lewismc** [comment]
Excellent

On Thu, Jun 18, 2015 at 1:49 PM, kohsah <notifications@github.com> wrote:

> 1.0.13 is on maven central now :
>
> <dependency>
>   <groupId>io.github.kohsah</groupId>
>   <artifactId>akomantoso-lib</artifactId>
>   <version>1.0.13</version>
> </dependency>
>
> Note that if you set maven to pickup "latest" it won't pick-up 1.0.13, you
> have to set version number explicitly..since maven-metadata.xml is not
> updated on central (there are various issues with setting latest in
> maven-metadata ... so I don't bother with that)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kohsah/akomantoso-lib/issues/10#issuecomment-113284788>
> .
>



-- 
*Lewis*
