### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by mkoniari** [kohsah/akomantoso-lib#12]
Hi, i was trying to create an AkomaNtoso act with the library. 
I am stuck at the the preamble element. 
For example what code will reproduce the following fragmanet 
```xml
<preamble>
	<p>
	An Act of Parliament to amend the Wildlife (Conservation and Management) Act to establish a
	Kenya Wildlife Service as a body corporate and for connected purposes
	</p>
	<formula name="enactedPreamble" currentId="formula1" class="preambleEnacted">
		<p>ENACTED by the Parliament of Kenya as follows:-</p>
	</formula>
</preamble>
```

**Comment by kohsah** [comment]
hi @mkoniari , 

I guess you are wondering how to create the "preamble" when there is no clear class for it ? 
"preamble" is a complex type in the XSD derived from "preambleopt". So you have to use ObjectFactory to create it : (createPreamble)[http://kohsah.github.io/akomantoso-lib/javadoc/1.0.13/org/akomantoso/schema/v3/csd13/ObjectFactory.html#createPreamble(org.akomantoso.schema.v3.csd13.Preambleopt)]. The code would look something like : 

```
ObjectFactory of = new ObjectFactory();
Preambleopt anpream = new Preambleopt ();
JAXBElement<Preambleopt > preamElem= 
    of.createPreamble(anpream );
```
At this preamElem is the "preamble" element and you can add a p or  formula to it ... 
I hope this answers your question ? I will add a section to the documentation on creating such complex types. 

Ashok

**Comment by lewismc** [comment]
@kohsah do you want to create a Google Group for this project?

**Comment by mkoniari** [comment]
i created one (https://groups.google.com/forum/#!forum/akomantoso-java-lib)
if you don't want i can delete it.

**Comment by lewismc** [comment]
Nice @mkoniari

**Comment by mkoniari** [comment]
Hi. once more i am stuck. 
I want to add some proprietary stuff like
```xml
 <proprietary source="#HB_bot">
                <dc:identifier>xyz</dc:identifier>
                <dc:source>abc</dc:source>
</proprietary>
```
and i don't know how to add content to Proprietary 
```Java
Proprietary e = new Proprietary();
e.setSource("#HB_bot");
```

**Comment by kohsah** [comment]
Hi @mkoniari 

The proprietary block can contain elements from any namespace. The library does not know in advance what namespace you can use. So you need to explicitly create the JAXB mapping for the namespace elements you want to use within the proprietary block (and even the Akoma Ntoso <foreign> element) .   Essentially you would extend the org.akomantoso.schema.v3.csd13.Proprietary, add setters and getters for the dc namespace elements. you would also need to create mapping classes for each DC element e.g : 

````
@XmlElement(name="identifier", namespace="http://dublincore.org/documents/2012/06/14/dces/")
public class DCIdentifier extends AnyOtherType {

}
```
Once that is done, you can use the extended Proprietary element for Marshalling. 

Unmarshalling will work out of the box though with the standard library , any foreign namespace elements within proprietary block will be available as standard DOM elements. 

Ashok

**Comment by mkoniari** [comment]
I really appreciate  your response to my questions and have to admit that things get out of my jaxb knowledge!
I created something like 
```Java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "identifier", namespace = "http://dublincore.org/documents/2012/06/14/dces/")

public class DCIdentifier extends AnyOtherType {
	@XmlElement(required = true)
    protected String value;
    public String getValue() {
        return value;
    }
    public void setValue(String value) {
        this.value = value;
    }
}
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "identifier", namespace = "http://dublincore.org/documents/2012/06/14/dces/")
public class DCIdentifier extends AnyOtherType {
	@XmlElement(required = true)
    protected String value;
    public String getValue() {
        return value;
    }
    public void setValue(String value) {
        this.value = value;
    }
}

usage 

DCProprietary e = new DCProprietary();
e.setSource("#HB_bot");
e.setGUID("...");
DCIdentifier dc_identifier = new DCIdentifier();
dc_identifier.setValue("marios");
e.setDcidentifier(dc_identifier);

output
<proprietary source="#HB_bot" href=".."/>
```
but i don't know how to continue 
Also don't i need to alter ObjectFactory with code like (... xjc generated)
```Java
      @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "identifier", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createIdentifier(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Identifier_QNAME, SimpleLiteral.class, null, value);
    }
```

**Comment by kohsah** [comment]
hi @mkoniari , let me try out your use case

**Comment by kohsah** [comment]
Hi @mkoniari  just had a quick look at this ...I think you hit a bug in the way the proprietary class was generated by JAXB because I checked the schema and it allows xs:Any while in the JAXB rendering of the class it seems to be missing. I will dig a bit deeper.

**Comment by kohsah** [comment]
H @mkoniari ... an update. Actually I have figured out how to set proprietary now : 

One easy way is to render your propritary elements as XML dom elements and set that to proprietary, this marshalls and unmarshalls correctly : 

```
        Meta meta = new Meta();
        // create the publication tag
        Publication pub = new Publication();
        pub.setWId("test_pub");
        pub.setName("pub");
        pub.setDate("2013-01-01");
        pub.setNumber("42");
        // add the publication element to the meta element
        meta.setPublication(pub);
        //create the identification element
        Identification idf = new Identification();
        idf.setSource("#a_source");
        //create a work element
        FRBRWork work = of.createFRBRWork();
        //set FRBRthis on work
        ValueType vThis = new ValueType();
        vThis.setValue("/ak/bill/2013-01-01/A1/memorandum");
        work.setFRBRthis(vThis);
        //set FRBRuri on work
        ValueType vURI = new ValueType();
        vURI.setValue("/ak/bill/2013-01-01/A1");
        work.getFRBRuri().add(vURI);
        //add the identification to the work
        idf.setFRBRWork(work);
        //add the identifcatin on the meta
        meta.setIdentification(idf);
        Proprietary propt = of.createProprietary();
        propt.setSource("#propriteray");
        propt.getAny().add(getTheElement()); // <<<< add DOM element of arbitrary element to proprietary
        meta.getProprietary().add(propt);   //<<<< add proprietary element to meta

```
getTheElement() is just a function that returns an arbitrary org.w3c.dom.Element : 

```
   private Element getTheElement() throws ParserConfigurationException {
       DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
		DocumentBuilder builder = dbf.newDocumentBuilder();
		Document doc = builder.newDocument();
		
		// create the root element node
		Element element = doc.createElement("root");
		doc.appendChild(element);

		// create a comment node given the specified string
		Comment comment = doc.createComment("This is a comment");
		doc.insertBefore(comment, element);

		// add element after the first child of the root element
		Element itemElement = doc.createElement("item");
		element.appendChild(itemElement);
		
		// add an attribute to the node
		itemElement.setAttribute("myattr", "attrvalue");
		
		// create text for the node
		itemElement.insertBefore(doc.createTextNode("text"), itemElement.getLastChild());
        return doc.getDocumentElement();
		
   }
```

If I convert the JAXB document to string i get this : 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<akomaNtoso xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD13">
    <doc contains="singleVersion" name="test_doc">
        <meta>
            <identification source="#a_source">
                <FRBRWork>
                    <FRBRthis value="/ak/bill/2013-01-01/A1/memorandum"/>
                    <FRBRuri value="/ak/bill/2013-01-01/A1"/>
                </FRBRWork>
            </identification>
            <publication date="2013-01-01" number="42" name="pub" wId="test_pub"/>
            <proprietary source="#propriteray">
                <root xmlns:ns2="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD13" xmlns="">
                    <item myattr="attrvalue">text</item>
                </root>
            </proprietary>
        </meta>
    </doc>

```

I will update the documentation with this. There is also another way to inject  another JAXB object within proprietary ... but I need to explore that further.  Hope this helps !

**Comment by kohsah** [comment]
Note -- I didnt change anything in ObjectFactory or any other generated classes.

**Comment by lewismc** [comment]
Nice

On Sun, Aug 30, 2015 at 10:56 PM, kohsah <notifications@github.com> wrote:

> H @mkoniari <https://github.com/mkoniari> ... an update. Actually I have
> figured out how to set proprietary now :
>
> One easy way is to render your propritary elements as XML dom elements and
> set that to proprietary, this marshalls and unmarshalls correctly :
>
>         Meta meta = new Meta();
>         // create the publication tag
>         Publication pub = new Publication();
>         pub.setWId("test_pub");
>         pub.setName("pub");
>         pub.setDate("2013-01-01");
>         pub.setNumber("42");
>         // add the publication element to the meta element
>         meta.setPublication(pub);
>         //create the identification element
>         Identification idf = new Identification();
>         idf.setSource("#a_source");
>         //create a work element
>         FRBRWork work = of.createFRBRWork();
>         //set FRBRthis on work
>         ValueType vThis = new ValueType();
>         vThis.setValue("/ak/bill/2013-01-01/A1/memorandum");
>         work.setFRBRthis(vThis);
>         //set FRBRuri on work
>         ValueType vURI = new ValueType();
>         vURI.setValue("/ak/bill/2013-01-01/A1");
>         work.getFRBRuri().add(vURI);
>         //add the identification to the work
>         idf.setFRBRWork(work);
>         //add the identifcatin on the meta
>         meta.setIdentification(idf);
>         Proprietary propt = of.createProprietary();
>         propt.setSource("#propriteray");
>         propt.getAny().add(getTheElement()); // <<<< add DOM element of arbitrary element to proprietary
>         meta.getProprietary().add(propt);   //<<<< add proprietary element to meta
>
>
> getTheElement() is just a function that returns an arbitrary
> org.w3c.dom.Element :
>
>    private Element getTheElement() throws ParserConfigurationException {
>        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
>         DocumentBuilder builder = dbf.newDocumentBuilder();
>         Document doc = builder.newDocument();
>
>         // create the root element node
>         Element element = doc.createElement("root");
>         doc.appendChild(element);
>
>         // create a comment node given the specified string
>         Comment comment = doc.createComment("This is a comment");
>         doc.insertBefore(comment, element);
>
>         // add element after the first child of the root element
>         Element itemElement = doc.createElement("item");
>         element.appendChild(itemElement);
>
>         // add an attribute to the node
>         itemElement.setAttribute("myattr", "attrvalue");
>
>         // create text for the node
>         itemElement.insertBefore(doc.createTextNode("text"), itemElement.getLastChild());
>         return doc.getDocumentElement();
>
>    }
>
> If I convert the JAXB document to string i get this :
>
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <akomaNtoso xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD13">
>     <doc contains="singleVersion" name="test_doc">
>         <meta>
>             <identification source="#a_source">
>                 <FRBRWork>
>                     <FRBRthis value="/ak/bill/2013-01-01/A1/memorandum"/>
>                     <FRBRuri value="/ak/bill/2013-01-01/A1"/>
>                 </FRBRWork>
>             </identification>
>             <publication date="2013-01-01" number="42" name="pub" wId="test_pub"/>
>             <proprietary source="#propriteray">
>                 <root xmlns:ns2="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD13" xmlns="">
>                     <item myattr="attrvalue">text</item>
>                 </root>
>             </proprietary>
>         </meta>
>     </doc>
>
>
> I will update the documentation with this. There is also another way to
> inject another JAXB object within proprietary ... but I need to explore
> that further. Hope this helps !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kohsah/akomantoso-lib/issues/12#issuecomment-136274068>
> .
>



-- 
*Lewis*

**Comment by mkoniari** [comment]
it works great. Thx!
