### ISSUE TITLE
Publish project Javadoc

### ISSUE THREAD

**Issue by lewismc** [kohsah/akomantoso-lib#7]
Javadoc are very comprehensive for this project.
It would be nice to maintain revisions moving forward. Maybe these can kept in the static gh-pages branch I think. 
There are a number of options here... we can implement this before the next library release... and hopefully back it in to the release profile.

http://khuxtable.github.io/wagon-gitsite/
or

```
* Commit the release pom.xml.
* Generate the JavaDocs to a .gitignore'd directory (so it would be preserved across branch changes).
* Checkout the gh-pages branch.
* Replace all of the files in the working directory with that of the directory the JavaDocs were copied to
* Commit
* Checkout the original branch.
* Continue with release...
```
My preference if for first option... if we can bake this in to a release profile then it is nice and clean.

**Comment by lewismc** [comment]
@kohsah the wagon plugin is more hassle than it's worth IMHO. Manually adding these to the gh-pages and making them current is a better more managed solution. Although it takes a bit more time (2 minutes) it ensures that versioning is correct, etc.

**Comment by kohsah** [comment]
@lewismc thanks for updating the javadoc.

**Comment by lewismc** [comment]
No at all

On Thursday, June 18, 2015, kohsah <notifications@github.com> wrote:

> @lewismc <https://github.com/lewismc> thanks for updating the javadoc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kohsah/akomantoso-lib/issues/7#issuecomment-113289017>
> .
>


-- 
*Lewis*
