### ISSUE TITLE
Library keeping up with AKN OASIS WG?

### ISSUE THREAD

**Issue by lewismc** [kohsah/akomantoso-lib#9]
Hi @kohsah I wonder if this lirbary is keeping up with the new AKN releases?
I was thinking about wrapping the akomantoso-lib as a Tika parser so that metadata could be extracted from AKN documents in a consistent manner as part of what Tika already does.
I didn't know of a better way to approach this than to open an issue Hope you are well.

**Comment by kohsah** [comment]
Hi Lewis,

I am on vacation at the moment, I will update it to csd 13 when I am back
near my computer next week. A tika plugin parser for Akoma Ntoso sounds
great !

Ashok

**Comment by lewismc** [comment]
Fantastic. Enjoy your holiday.
I'll update you here once I finish with the Tika plugin.
Thanks and all the best
Lewis

On Thu, Jan 8, 2015 at 1:16 AM, kohsah <notifications@github.com> wrote:

> Hi Lewis,
>
> I am on vacation at the moment, I will update it to csd 13 when I am back
> near my computer next week. A tika plugin parser for Akoma Ntoso sounds
> great !
>
> Ashok
> On 07-Jan-2015 4:58 pm, "Lewis John McGibbney" <notifications@github.com>
> wrote:
>
> > Hi @kohsah <https://github.com/kohsah> I wonder if this lirbary is
> > keeping up with the new AKN releases?
> > I was thinking about wrapping the akomantoso-lib as a Tika parser so
> that
> > metadata could be extracted from AKN documents in a consistent manner as
> > part of what Tika already does.
> > I didn't know of a better way to approach this than to open an issue
> Hope
> > you are well.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kohsah/akomantoso-lib/issues/9>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kohsah/akomantoso-lib/issues/9#issuecomment-69153951>.
>



-- 
*Lewis*

**Comment by kohsah** [comment]
New release synced to Akoma Ntoso CSD13. See https://github.com/kohsah/akomantoso-lib/releases/tag/1.0.13
